name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-11-jdk
          
      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true
          echo "Licenses accepted"
          
      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33
        
      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: waiter-dashboard.apk
          path: bin/*.apk
