name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-11-jdk wget unzip

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk
          mv ~/android-sdk/cmdline-tools ~/android-sdk/latest
          echo "export ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:~/android-sdk/latest/bin" >> $GITHUB_ENV

      - name: Accept licenses
        run: |
          yes | ~/android-sdk/latest/bin/sdkmanager --licenses || true
          ~/android-sdk/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0"

      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          export PATH=$PATH:~/android-sdk/build-tools/36.0.0:~/android-sdk/platform-tools
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: waiter-dashboard.apk
          path: bin/*.apk
